FROM golang:latest as builder

WORKDIR /go/src/github.com/dungeonmaster18/demo/

RUN go get -d -v github.com/gorilla/mux
COPY app.go	.

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /go/src/github.com/dungeonmaster18/demo/app    .

CMD ["./app"]